### ISSUE TITLE
GenerateDependencyObject bug

### ISSUE THREAD

**Issue by HppZ** [CommunityToolkit/Lottie-Windows#491] opened 2022-02-21 08:46 UTC
`.\LottieGen.exe -Language cs -GenerateColorBindings -GenerateDependencyObject -WinUIVersion 2.7 -OutputFolder output\ -InputFile`

when `-GenerateDependencyObject` is set, `public void SetColorProperty(string propertyName, Color value)` is not right.
![image](https://user-images.githubusercontent.com/12285582/154919434-263d0161-6eec-406b-b29c-6f11aac24574.png)

**Comment by aborziak-ms** [comment] 2022-02-22 20:46
Have you tried `-WinUIVersuin 2.6`? There could be a bug with 2.7 version in LottieGen, I will take a look.

**Comment by HppZ** [comment] 2022-02-23 11:30
> Have you tried -WinUIVersuin 2.6?

No, please fix it.

**Comment by huynhsontung** [comment] 2023-10-22 01:49
Confirmed the issue is still there when running with WinUI version 2.6, 2.7, or 2.8. The workaround is easy, just remove the `_theme` prefix. For example, `_themeColor_XXXXXX` should be renamed to `Color_XXXXXX`.

**Comment by aborziak-ms** [comment] 2024-02-27 18:23
Fixed in #548

**Closed by aborziak-ms** 2024-02-27 18:23 UTC
