### ISSUE TITLE
LT0016 Path with round corners is not supported

### ISSUE THREAD

**Issue by ZodmanPerth** [CommunityToolkit/Lottie-Windows#445] opened 2021-05-06 03:04 UTC
Our animators use animated paths with round corners as a tool for animating the cutting of one shape into two.  We were surprised to find that a path with round corners is not supported, as they do seem a basic primitive that is reasonably common in use.

We would greatly appreciated if Lottie-Windows could add support for paths with round corners.

**Comment by aborziak-ms** [comment] 2021-06-25 23:41
Recently we added partial support of this feature in #451 and #452. Does it fit your use case?

**Comment by ZodmanPerth** [comment] 2021-06-26 07:08
In the end our animator used After Effects to make a lottie animation that created shapes and cycled them at 60fps (stop motion style) to past the issue.

I think change #452 will be required for our case.  Once the changes get into the Lottie Viewer app I can re-run the scenario against the old animation to see if it sorts it.

Here's the specific errors reported by the Lottie Viewer in case it helps.

![image](https://user-images.githubusercontent.com/546368/123505215-67339300-d690-11eb-83c4-505c2d4f1950.png)

**Comment by aborziak-ms** [comment] 2021-07-22 18:54
We just merged #452 to master. Also now it should report issue LT0043 (not fully supported) instead of LT0016. The problem is that the way that we are drawing on the screen does not allow us to draw animated rounded corners that are pixel-perfect to After Effects. But resulting shapes are very close.

**Closed** 2021-09-17 17:01 UTC
