### ISSUE TITLE
LottieGen generates faulty optimized animation

### ISSUE THREAD

**Issue by FrayxRulez** [CommunityToolkit/Lottie-Windows#513] opened 2022-07-28 09:01 UTC
The attached animation only generates a working `.cs` when `-DisableTranslationOptimizer` flag is included.

Omitting it will cause the animation to render like this, and do nothing on play:
![image](https://user-images.githubusercontent.com/8152849/181464836-6d7052ed-ef10-44b9-bb44-2215ce81eff1.png)

Here's a video of how it should look like:
![chrome_c5MMZJX4Hw](https://user-images.githubusercontent.com/8152849/181466248-2e862211-2334-472d-b1ce-a1127df81ce2.gif)

[VoiceRecognition.zip](https://github.com/CommunityToolkit/Lottie-Windows/files/9207489/VoiceRecognition.zip)

**Comment by aborziak-ms** [comment] 2022-08-02 17:23
Thanks, I will take a look. There are some known issues with the optimizer

**Comment by aborziak-ms** [comment] 2022-08-16 23:29
@FrayxRulez I was not able to reproduce this bug. What are the command lines arguments that you've used? And what is the version of LottieGen. I think it might be useful to attach generate .cs file as well. Thank you

**Comment by aborziak-ms** [comment] 2024-02-28 19:16
I was not able to repro this exact bug, but I saw a similar one, that looked very similar to first screenshot. Should be fixed by #551

**Closed by aborziak-ms** 2024-02-28 19:16 UTC
Labels: bug
